---
- name: playbook to create directory
  hosts: all
  become: true
  tasks:
  - name: creating a file
    file:
      path: /home/ansadmin/test.txt
      state: touch
      mode: 0777
      owner: ansadmin
